kind: pipeline
type: docker
name: default

steps:
  - name: docker  
    image: plugins/docker
    settings:
      debug: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: larsstoker/netbox
      tags: latest